// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3r_dO435WhlB8pD_oG4e_Fu4bL-jigbE',
    appId: '1:87323836197:web:a5996b6fa5d415c95864cc',
    messagingSenderId: '87323836197',
    projectId: 'exercise-5a-auth',
    authDomain: 'exercise-5a-auth.firebaseapp.com',
    storageBucket: 'exercise-5a-auth.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAM-9lvRPGy5MGvhEo3aMbJ0ZxBVhRxKBM',
    appId: '1:87323836197:android:48f356dd41922bb55864cc',
    messagingSenderId: '87323836197',
    projectId: 'exercise-5a-auth',
    storageBucket: 'exercise-5a-auth.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCocv25bR5WxMouUpezjWslMKy_nPjjq2Y',
    appId: '1:87323836197:ios:39eaa9956bb8b3345864cc',
    messagingSenderId: '87323836197',
    projectId: 'exercise-5a-auth',
    storageBucket: 'exercise-5a-auth.firebasestorage.app',
    iosBundleId: 'com.example.exercise5a',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCocv25bR5WxMouUpezjWslMKy_nPjjq2Y',
    appId: '1:87323836197:ios:39eaa9956bb8b3345864cc',
    messagingSenderId: '87323836197',
    projectId: 'exercise-5a-auth',
    storageBucket: 'exercise-5a-auth.firebasestorage.app',
    iosBundleId: 'com.example.exercise5a',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3r_dO435WhlB8pD_oG4e_Fu4bL-jigbE',
    appId: '1:87323836197:web:4ee12177d4d605115864cc',
    messagingSenderId: '87323836197',
    projectId: 'exercise-5a-auth',
    authDomain: 'exercise-5a-auth.firebaseapp.com',
    storageBucket: 'exercise-5a-auth.firebasestorage.app',
  );
}
